### ISSUE TITLE
Missing icons for scala, erlang, and clojure in 'app components' tab of new app

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#1]
As seen here - 
![image](https://cloud.githubusercontent.com/assets/2653109/19530028/59361bce-95ef-11e6-94ca-953c33aeeeae.png)

**Comment by glinton** [comment]
Now it's just missing icons for go and clojure - 
![image](https://cloud.githubusercontent.com/assets/2653109/21994273/23c58348-dbdc-11e6-8f0e-8eaae4be1e31.png)

**Comment by glinton** [comment]
![image](https://cloud.githubusercontent.com/assets/2653109/21994304/477a917a-dbdc-11e6-876a-33bd3fb231e3.png)

**Comment by Tolmark12** [comment]
@jedgalbraith I forget, do we still show this?

**Comment by jedgalbraith** [comment]
@Tolmark12 Yes, we do. When no app components have been deployed. Here's an example of a live app https://dashboard.nanobox.io/apps/caf267bc-a20e-4ce5-8f8b-d92ce42f7c6a (unless the user has deployed to it recently)
