### ISSUE TITLE
Clarify admin actions

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#14]
Although it seems the available actions (particularily reboot/rebuild) for a platform service apply to *all* containers, I'm sure this isn't the case. What *does* it mean?

![image](https://cloud.githubusercontent.com/assets/2653109/22575060/684d9086-e970-11e6-8454-aec2c88d396d.png)

![image](https://cloud.githubusercontent.com/assets/2653109/22575139/ffe1a478-e970-11e6-8090-61c3ae175fe2.png)

**Comment by Tolmark12** [comment]
I believe it is all containers inside this component no? @tylerflint thoughts?

**Comment by jedgalbraith** [comment]
Yes, that's right. It's all containers inside the component.
