### ISSUE TITLE
Long droplet hostnames push stats face off droplet's card

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#16]
![image](https://cloud.githubusercontent.com/assets/2653109/22745561/413d75a2-edde-11e6-8f0e-2215a2107d02.png)

![image](https://cloud.githubusercontent.com/assets/2653109/22745552/37828ca0-edde-11e6-83e0-cebcb2dc7597.png)

Also, the host information overflows the tile (when viewing 'hosts')
![image](https://cloud.githubusercontent.com/assets/2653109/22745613/6eeac8b0-edde-11e6-9221-43142a722a94.png)

![image](https://cloud.githubusercontent.com/assets/2653109/22745796/ff06e528-edde-11e6-9398-9ae0aa1481c8.png)

**Comment by Tolmark12** [comment]
Pushed a fix, ready for deploy : `bower update clobberbox`

**Comment by jedgalbraith** [comment]
Looks good.
