### ISSUE TITLE
"no app components deployed" box doesn't go away after deploy to new app

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#2]
![image](https://cloud.githubusercontent.com/assets/2653109/19530102/b4577e62-95ef-11e6-9521-e2ed56a9fb9d.png)
It does go away after a page refresh - 
![image](https://cloud.githubusercontent.com/assets/2653109/19530124/c6eb3488-95ef-11e6-936c-00b6419837d0.png)

**Comment by glinton** [comment]
Still an issue:
![image](https://cloud.githubusercontent.com/assets/2653109/21994470/16f2c59e-dbdd-11e6-9b4e-c6601e5c23aa.png)

Possibly related to #9

**Comment by Tolmark12** [comment]
Fixed, ready for deploy : `bower update clobberbox`

**Comment by jedgalbraith** [comment]
deployed
