### ISSUE TITLE
Remove 'Ready for app deploy' until platform services are complete

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#22]
Currently, as soon as the bunkhouse is created, users see the 'ready for app deploy', but upon deploying `nanobox deploy` fails

![image](https://cloud.githubusercontent.com/assets/2653109/23816020/bac23e68-05a7-11e7-9ee8-a9b9bdf858d6.png)

`nanobox deploy` output
```
Deploying app :
  ✓ Starting docker container
  ! Uploading
- Sending app...
- Generating compressed tarball of app...
  Sending app: 
  Sending app: curl: (6) Could not resolve host: 

! FAILED TO PUBLISH DEPLOY !

Exit
 6

Command
 siphon --prefix '  Sending app: ' -- curl -k -f --progress-bar -o /dev/null -H 'x-auth-token: abc' --data-binary @/var/tmp/app-123.tgz https://:7410/blobs/app-123.tgz

Output
   Sending app: 
   Sending app: curl: (6) Could not resolve host: 


Error   : failed to execute hook (publish) on d56a55e9f9aba528bc1dfffa6c2f653d7d1c2ccd0a496878b41588cca55cdf32: util:Exec:/opt/nanobox/hooks/publish: bad exit code(1): 
Context : failed to publish build to app's warehouse -> failed to run publish hook
```

The cli doesn't get back an address for hoarder, because it hasn't finished building yet.

**Comment by Tolmark12** [comment]
I'm not sure how we can know when it's ready for deploy. I think that's just shown when : 
`totalDeploys == 0`

**Comment by jedgalbraith** [comment]
The only other way I can think of is to base it on the state of the platform services. I could pass a separate attribute that indicates they're ready. Maybe `isPlatformReady`? So then you'd display the 'Ready for app deploy' when `totalDeploys == 0 && isPlatformReady == true`. And maybe we should display something else in the meantime indicating the platform is being prepared or something?

**Comment by Tolmark12** [comment]
yeah, we could add an API method to be called by rails once the app is ready since valkrie is passive; ie not listening for event notifications. Maybe something like `changeDeployReadiness( 'ready' )`

**Comment by Tolmark12** [comment]
Just spoke with Jed who reminded me how valkrie is updated, we'll move forward with an assumption that `isPlatformReady:boolean` will be passed in indicating if an app may be deployed.

**Comment by Tolmark12** [comment]
Feature added, ready for deploy. 

bower update `clobberbox, valkrie`

Expecting `isPlatformReady` boolean at the root level of the data glob.

**Comment by jedgalbraith** [comment]
@Tolmark12 I was assuming that @glinton was also implying that we should remove the deploy instructions as well until the platform is ready. I think even though the message is now "Installing Platform", since the instructions are there, I think users will still assume they can go ahead and deploy. Thoughts?

![screen shot 2017-04-11 at 12 41 06 pm](https://cloud.githubusercontent.com/assets/313947/24925239/db3c50a4-1eb4-11e7-91b6-f95f21e3045f.png)

**Comment by Tolmark12** [comment]
I'm wondering if we can show a message to the user if they try to deploy to an app that is created, but where the platform hasn't yet installed yet. Something like:

`We are installing the platform on some-app's, new server. As soon as that is complete, try your deploy again`

We want to keep the deploy instructions visible for those that follow the following path:

1) Sign up for nanobox
2) Create a new app (just testing things out)
3) View instructions for deploying an app including the first steps which are primarily about the local dev tool

**Comment by jedgalbraith** [comment]
That's a possibility. I'll see what I can do.

**Comment by Tolmark12** [comment]
that would need to be in the CLI, correct?

**Comment by jedgalbraith** [comment]
yes, in the CLI, but I'll need to adjust how Odin responds to a deploy request from the CLI and send back the proper messaging.

**Comment by jedgalbraith** [comment]
So the request this involves is actually a request the CLI makes for platform service info for warehouse, before it attempts to upload the deploy. So since this needs to apply to multiple platform services and multiple scenarios, I've adapted the messages a bit.

Here's what the CLI messaging looks like if there is no warehouse platform service yet:
```
Error   : Not Found ({"error":"The warehouse platform service for app-name is not yet installed. As soon as that is complete, try again."})
Context : unable to generate warehouse config -> failed to fetch warehouse information from nanobox
```
And this is what it looks like it there is a warehouse, but it's not active yet:
```
Error   : The warehouse platform service for app-name is not yet active. As soon as that is complete, try again.
Context : unable to generate warehouse config -> failed to fetch warehouse information from nanobox
```

**Comment by jedgalbraith** [comment]
deployed
