### ISSUE TITLE
`Update Agent` button in dashboard doesn't life cycle

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#24]
![image](https://cloud.githubusercontent.com/assets/2653109/25046920/429745d6-20f1-11e7-9116-ef441fd7b442.png)

There seemed to be a deploy going on when I clicked, so I didn't immediately notice that clicking this added a number to the number of tasks. I did finally notice that it does create a task and show that it's running, but otherwise there is no clear indication that clicking it worked.
![image](https://cloud.githubusercontent.com/assets/2653109/25047009/afb69fae-20f1-11e7-8e3d-8e12582a590a.png)

**Comment by jedgalbraith** [comment]
Fixed. Now it uses the same button/styles as other save buttons.

![](http://g.recordit.co/tam4SUJKvs.gif)
