### ISSUE TITLE
Add link to (updated) docs for connecting to production storage node in dashboard

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#25]
Currently, the dashboard refers to console output for port to connect to:
![image](https://cloud.githubusercontent.com/assets/2653109/25359624/1ce79dc6-2903-11e7-969d-1dd9c487a9fd.png)

Note it doesn't reference a user either. Luckily there is [this doc](https://docs.nanobox.io/data-management/managing-live-data/), but unfortunately it doesn't currently work:
![image](https://cloud.githubusercontent.com/assets/2653109/25359675/51e41c66-2903-11e7-89ed-1475c94aa228.png)
After the authentication failures message, it hangs until either the `scp` or `nanobox tunnel` command receives a `SIGINT`. Either docs or storage node seems to need updating for tunneling to work.

Specifying the user to connect with in the dashboard may even negate the need for a link to the docs.

**Comment by jedgalbraith** [comment]
This is related to https://github.com/nanobox-io/nanobox-docker-unfs/issues/15. The `nanobox/unfs` image needs to return a default user that Odin can display.

**Comment by jedgalbraith** [comment]
The credentials are now included for `nanobox/unfs` components.

![screen shot 2017-04-25 at 2 51 53 pm](https://cloud.githubusercontent.com/assets/313947/25407294/0be56c32-29c7-11e7-9d5d-281e7c5b0804.png)
