### ISSUE TITLE
Cancelling deploy shows old instances are getting removed

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#27]
![image](https://user-images.githubusercontent.com/2653109/27195133-c3aabac0-51c2-11e7-9004-807cfe4f9d99.png)

When I cancelled a deploy, I saw this and was thrown off thinking that it was keeping my old, broken instances then I realized/verified it was just a typo. Probably not huge priority

**Comment by jedgalbraith** [comment]
I've reworded to just `destroying instances` since the message is used in multiple contexts.
