### ISSUE TITLE
Bad flow when trying to scale a component when the upgrade isn't activated

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#29]
I went through the steps to configure my scale:
![image](https://user-images.githubusercontent.com/2653109/27649429-f8010b86-5bee-11e7-96ce-d2718f575901.png)

To be told I need to activate an upgrade: (I assume I'd be brought back and the scale would complete)
![image](https://user-images.githubusercontent.com/2653109/27649448-0959e286-5bef-11e7-83bf-bb7ae218358a.png)

To my dissapointment, my configuration was lost and I was not redirected:
![image](https://user-images.githubusercontent.com/2653109/27649394-dfb797b6-5bee-11e7-80e8-cf3b31e146d7.png)

Requiring me to go back through all the steps to configure the scale.

Seems that we should either redirect back, and apply the desired scale/move/etc... or require the upgrade prior to accessing the 'scale/move/etc...' tab.

**Comment by jedgalbraith** [comment]
This is being addressed with the new pricing changes coming out soon.
