### ISSUE TITLE
Failed sequence error message doesn't clear after success

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#32]
After 'retry'ing a failed sequence from the dashboard and it succeeding, the error remains for the duration of the deploy (unless the page is refreshed)
![image](https://user-images.githubusercontent.com/2653109/27696185-3d5230e2-5cae-11e7-80a0-027aac7c833e.png)

**Comment by jedgalbraith** [comment]
I'm pretty sure this is fixed now. Let me if not.
