### ISSUE TITLE
Cannot access dashboard with Chromium

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox-dashboard-issues#5]
_From @mbrodala on November 3, 2016 9:41_

If I try to open the dashboard with Chromium, I am redirected to the following error page:

https://dashboard.nanobox.io/426

This should be fixed since Chromium is essentially the same as Chrome minus a few non-free pieces.

_Copied from original issue: nanobox-io/nanobox#238_

**Comment by lyondhill** [comment]
_From @glinton on November 3, 2016 15:25_

@mbrodala What version of Chromium are you running and do you have any extensions that may interfere?

**Comment by lyondhill** [comment]
we are using a project called Modernizr to determine if your browser has the required features. The list of features we currently require are [here](https://modernizr.com/download/?borderradius-boxshadow-boxsizing-canvas-checked-cookies-cors-cssanimations-csspointerevents-csspseudoanimations-csspseudotransitions-csstransforms-csstransitions-cssvalid-displaytable-ellipsis-es5-eventlistener-flexbox-fontface-formvalidation-generatedcontent-hashchange-hiddenscroll-history-inlinesvg-input-inputtypes-json-lastchild-localstorage-mediaqueries-nthchild-opacity-placeholder-queryselector-requestanimationframe-rgba-sessionstorage-siblinggeneral-svg-svgasimg-svgclippaths-svgfilters-target-unicode-userselect-websockets-setclasses)

you can use the in browser javascript console to see the list of features your browser is missing.

**Comment by lyondhill** [comment]
_From @mbrodala on November 3, 2016 15:41_

Re-posted from Slack:

> Version 53.0.2785.143 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

Console says:

```
Modernizr_hiddenscroll: false
Modernizr_csspseudoanimations: false
Modernizr_csspseudotransitions: false
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Failed to load resource: the server responded with a status of 426 (Upgrade Required)
```

**Comment by lyondhill** [comment]
im using `53.0.2785.143 (Developer Build) Built on Ubuntu` and its working for me. one of your chrome extensions may be getting in the way.

**Comment by lyondhill** [comment]
_From @mbrodala on November 3, 2016 15:50_

Just tried Incognito mode where no extension is enabled but still no luck.

**Comment by lyondhill** [comment]
_From @mbrodala on November 3, 2016 16:15_

I was able to fix the `localStorage` security error by adding an exception for `static.olark.com`. (see [background](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document))

**Comment by sdomino** [comment]
Resolved in https://github.com/nanobox-io/odin/commit/6033334dbbce0993dd2c4289e51386bd51857d7b

**Comment by mbrodala** [comment]
@sdomino Could it be that that repository is private? Both the commit as well as the repository throw a 404.

**Comment by sdomino** [comment]
@mbrodala you are correct, that is a private repo. I wanted to reference it here for our (internal) benefit, however I should have mentioned that in the message. That change has been deployed if you want to try again and see if you're able to access the dashboard.

**Comment by mbrodala** [comment]
Thanks for the info, I'll check ASAP.
