### ISSUE TITLE
App not accessible after scaling up

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox-dashboard-issues#6]
_From @mbrodala on December 20, 2016 9:4_

I just scaled up my app on DO from the $5 to the $10 droplet via Nanobox' dashboard and now the app is not accessible anymore.

I currently get `HTTP/1.1 502 Bad Gateway` instead.

Neither container/platform health nor logs give an idea of the error.

_Copied from original issue: nanobox-io/nanobox#309_

**Comment by jedgalbraith** [comment]
The fix has been deployed. 

The issue was related to the “Mesh Sync” process. That’s the process that informs the router/load-balancer where new containers are located. During the scale of a multi-component host, there are two points where that needs to happen. The second one wasn’t happening.
