### ISSUE TITLE
Bunkhouse `delete` button doesn't lifecycle

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#7]
There may no longer be issues with clicking this multiple times, but it seems that it may have at one point

**Comment by Tolmark12** [comment]
Added a lifecycle to all the actions (including deltee). I then remove the lifecycle when the http call returns successful. 

Note : a successful call may not equal a successfully completed action; so this may not be exactly what we are looking for...

bower update `clobberbox`

**Comment by Tolmark12** [comment]
Just tested this out, and it only lifecycles during the submission of the request. if we want a true lifecycle, we need a way to track the state of each action.

**Comment by jedgalbraith** [comment]
I think the lifecycle during the request, like it is now,  is fine. It gives you some feedback so you know you clicked it. Tracking state beyond that would be quite complex and error prone. And with some of the buttons, it's a valid action to click again before it's complete.

**Comment by Tolmark12** [comment]
Agreed.
