### ISSUE TITLE
Dashboard stats don't update

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#9]
![image](https://cloud.githubusercontent.com/assets/2653109/21991345/7686e746-dbcf-11e6-9157-731733e94748.png)

Ram usage could be at 80% but dashboard stats wouldn't reflect it until a page refresh.

Ubuntu 16.10, Chrome Version 55.0.2883.87 (64-bit)

**Comment by glinton** [comment]
Another example - 
![image](https://cloud.githubusercontent.com/assets/2653109/23238237/40f157c6-f91e-11e6-9d27-d256397d60e2.png)
The combined stats didn't update, as evident but the more recently requested warehouse stats

**Comment by Tolmark12** [comment]
Feature added. Live status should now update once every minute. 

bower update : `clobberbox, valkrie, hourly-stats`

**Comment by jedgalbraith** [comment]
deployed
